name: CI workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      - name: CodeQL Analysis
        uses: github/codeql-action@v1
        with:
          languages: python
      - name: Generate Documentation
        run: |
          pip install -r doc-requirements.txt
          sphinx-build -b html docs/ docs/_build
        if: success()
      - name: Dependency Security Scanning
        uses: github/code-scanning-action@v1
        with:
          scan-id: 'dependency-scanning'
          # Additional configuration options can be added as needed
      - name: Build and Deploy
        run: |
          # Add your deployment script here
        if: success()      
